import {central,slug,esc} from './shared.mjs';
const by=id=>document.getElementById(id);
export function sheet(title,head,rows){return '<!doctype html><html lang="en"><meta charset="utf-8"><title>'+esc(title)+'</title><style>body{font:16px Arial;margin:32px;color:#14343e}table{border-collapse:collapse;width:100%}th,td{border:1px solid #aaa;padding:12px;text-align:left}h1{font-size:24px}@media print{button{display:none}}</style><h1>'+esc(title)+'</h1><button onclick="window.print()">Print / save PDF</button><table><thead><tr>'+head.map(x=>'<th>'+esc(x)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+r.map(x=>'<td>'+esc(x)+'</td>').join('')+'</tr>').join('')+'</tbody></table></html>'}
export function registerSheet(state,group,date,period,blank){const pupils=state.students.filter(p=>!p.archived&&(p.classIds.includes(group.id)||p.tutorId===group.id)).sort((a,b)=>a.last.localeCompare(b.last));return sheet(state.school.name+' · '+group.name+' · '+date+' · '+(Number(period)?'P'+period:'Tutor register'),['Student','Mark','Status'],pupils.map(p=>{const a=state.attendance.find(a=>a.studentId===p.id&&a.date===date&&a.period===Number(period));return[p.last+', '+p.first,blank?'□':!a?'—':['present','late'].includes(a.mark)?'✓':'✗',blank?'':a?.mark||'Not recorded']}))}
function download(filename,body){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([body],{type:'text/html;charset=utf-8'}));a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
let demoData={reasons:['Disruption','Missed homework','Late to lesson','Uniform'],records:[],canEdit:true,canPolicy:true};
export async function mountDetentions(state,isDemo,toast){const host=by('detention-area');if(!host)return;let data;
const request=async(action='list',payload={})=>{if(!isDemo)return central('ol_detentions',{p_slug:slug,p_action:action,p_data:payload});if(action==='policy')demoData.reasons=payload.reasons;if(action==='create')demoData.records.push({...payload,id:crypto.randomUUID(),student_id:payload.studentId,day:payload.date,start_time:payload.time,status:'Scheduled'});if(action==='status')demoData.records.find(x=>x.id===payload.id).status=payload.status;return structuredClone(demoData)};
const run=fn=>async e=>{e.preventDefault();try{await fn()}catch(err){toast(err.message,'bad')}};
const draw=()=>{if(!host.isConnected)return;host.innerHTML=`<div class="page-head"><div><p>BEHAVIOUR FOLLOW-UP</p><h1>Detentions</h1><span>${isDemo?'Demo changes are temporary.':'Detention changes save immediately.'}</span></div></div><div class="two-col"><form id="detention-add" class="card"><h2>Add a detention</h2><label>Student<select id="dt-pupil" required>${state.students.filter(p=>!p.archived).map(p=>`<option value="${esc(p.id)}">${esc(p.last+', '+p.first)} · Year ${p.year}</option>`).join('')}</select></label><label>Reason<select id="dt-reason">${data.reasons.map(r=>`<option>${esc(r)}</option>`).join('')}</select></label><label>Date<input id="dt-date" type="date" required></label><label>Time<input id="dt-time" type="time" value="15:00" required></label><label>Minutes<input id="dt-minutes" type="number" min="5" max="180" value="30" required></label><label>Location<input id="dt-location" maxlength="120" required></label><button class="btn primary" ${data.canEdit?'':'disabled'}>Add detention</button></form><form id="detention-policy" class="card"><h2>Detention reasons</h2><p>One dropdown reason per line. Previous detention records keep their original reason.</p><label>Reasons<textarea id="dt-reasons" rows="7">${esc(data.reasons.join('\n'))}</textarea></label><button class="btn soft" ${data.canPolicy?'':'disabled'}>Save reasons</button></form></div><article class="card"><div class="card-head"><h2>Detention board</h2><label>Date filter<input id="dt-filter" type="date"></label><button id="dt-download" class="btn soft">Download board</button><button id="dt-refresh" class="btn soft">Refresh</button></div><div id="dt-board" style="overflow:auto"></div></article>`;
const rows=()=>data.records.filter(x=>!by('dt-filter').value||x.day===by('dt-filter').value);
const pname=x=>{const p=state.students.find(p=>p.id===x.student_id);return p?p.last+', '+p.first:'Former student'};
const board=()=>{by('dt-board').innerHTML='<table><tr><th>Student</th><th>Date / time</th><th>Reason</th><th>Location</th><th>Duration</th><th>Status</th></tr>'+rows().map(x=>`<tr><td>${esc(pname(x))}</td><td>${esc(x.day)} ${esc(x.start_time.slice(0,5))}</td><td>${esc(x.reason)}</td><td>${esc(x.location)}</td><td>${x.minutes} min</td><td><select data-dt-status="${esc(x.id)}" ${data.canEdit?'':'disabled'}>${['Scheduled','Attended','Missed','Cancelled'].map(v=>`<option ${x.status===v?'selected':''}>${v}</option>`).join('')}</select></td></tr>`).join('')+'</table>';host.querySelectorAll('[data-dt-status]').forEach(el=>el.onchange=run(async()=>{data=await request('status',{id:el.dataset.dtStatus,status:el.value});board()}))};board();by('dt-filter').onchange=board;
by('detention-add').onsubmit=run(async()=>{data=await request('create',{studentId:by('dt-pupil').value,reason:by('dt-reason').value,date:by('dt-date').value,time:by('dt-time').value,minutes:Number(by('dt-minutes').value),location:by('dt-location').value});draw();toast('Detention saved')});
by('detention-policy').onsubmit=run(async()=>{data=await request('policy',{reasons:[...new Set(by('dt-reasons').value.split('\n').map(s=>s.trim()).filter(Boolean))]});draw();toast('Detention reasons saved')});
by('dt-refresh').onclick=run(async()=>{data=await request();draw()});by('dt-download').onclick=()=>download('detention-board.html',sheet(state.school.name+' · Detention board'+(by('dt-filter').value?' · '+by('dt-filter').value:''),['Student','Date','Time','Reason','Location','Minutes','Status'],rows().map(x=>[pname(x),x.day,x.start_time.slice(0,5),x.reason,x.location,x.minutes,x.status])))};
try{data=await request();draw()}catch(e){if(host.isConnected)host.innerHTML='<article class="card"><h2>Detentions setup</h2><p>'+esc(e.message)+'</p><p>Run ONEEDUCATION-DETENTIONS-UPGRADE.sql from this update in your platform Supabase project.</p></article>'}}
