import * as C from './core.mjs';
const e=(v='')=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const brand='<img src="oneeducation-mark.svg" alt="" width="32" height="32"><strong>OneEducation</strong>';
const groups=[['Workspace',['home','staffhub','helpdesk']],['Students',['students','pupil-records','tutors','class-allocation','manage-pupils','manage-sats']],['Teaching',['classes','manage-classes','manage-timetable','attendance','homework','revision','exams','cover','availability']],['Pastoral',['behaviour','detentions','oncall','reports','evenings','activities']],['School',['campus','manage-rooms','manage-staff','manage-houses','school']],['Administration',['admin','staff-accounts','manage-policies','funding','lockdown-control']]];
const initials=n=>e(n.split(/[\s@.]+/).filter(Boolean).slice(0,2).map(s=>s[0]).join('').toUpperCase());
const link=(r,t,cl='')=>`<a class="${cl}" href="#${r}" data-route="${r}">${e(t)} <span aria-hidden="true">↗</span></a>`;
const empty=s=>`<p class="dash-empty">${e(s)}</p>`;
const card=(title,body,action='')=>`<article class="card dash-card"><div class="dash-card-head"><h2>${e(title)}</h2>${action}</div>${body}</article>`;
export function staffShell({state,nav,canRoute,route,who,role,demo,dirty,content}){
 const menu=groups.map(([title,ids])=>{const rows=ids.map(id=>nav.find(n=>n[0]===id)).filter(n=>n&&canRoute(n[0]));return rows.length?`<details class="nav-group" ${rows.some(n=>n[0]===route)||title==='Workspace'?'open':''}><summary>${e(title)}</summary>${rows.map(([id,icon,label])=>`<a href="#${id}" data-route="${id}" ${id===route?'aria-current="page"':''} class="${id===route?'active':''}"><b aria-hidden="true">${icon}</b><span>${e(label)}</span></a>`).join('')}</details>`:''}).join('');
 return `<div class="shell redesign"><header class="suite-header"><button class="mobile-menu" id="mobileMenu" aria-label="Toggle navigation" aria-expanded="false">☰</button><a class="suite-brand" href="#home" data-route="home">${brand}</a><div class="suite-name">${e(state.school.name)}</div><label class="global-search"><span aria-hidden="true">⌕</span><input aria-label="Search students and classes" id="globalSearch" placeholder="Search students and classes…" autocomplete="off"><div id="searchResults"></div></label><span class="user-badge" title="${e(who)}">${initials(who)}</span><button id="signOut" title="Sign out">Sign out</button></header><aside class="rail"><div class="rail-intro"><span>YOUR WORKSPACE</span><strong>${demo?'Interactive demo':e(role.replaceAll('_',' '))}</strong></div><nav aria-label="Main navigation">${menu}</nav><div class="rail-status"><i class="${C.schoolClosed(state)?'closed':''}"></i><div><strong>${C.schoolClosed(state)?'School closed / closing':'School open'}</strong><small>Week ${C.weekForDate(state,C.today())} · ${e(C.nice(C.today()))}</small></div></div></aside><div class="workspace"><main id="main" tabindex="-1">${content}</main><footer class="savebar"><span id="saveNote">${demo?'Demo workspace · sample data · no live changes':'OneEducation · '+e(state.school.name)}</span><button id="saveState" class="btn primary" ${demo||!dirty?'disabled':''}>${demo?'Demo mode':dirty?'Save changes':'All changes saved'}</button></footer></div></div>`;
}
export function staffDashboard({state,canRoute,capabilities,demo,email,year=''}){
 const admin=demo||capabilities.policies||capabilities.accounts;
 const t=C.today(),day=C.weekday(t),teacher=state.teachers.find(x=>(x.email||'').toLowerCase()===(email||'').toLowerCase());
 const mine=teacher?state.classes.filter(c=>c.teacherId===teacher.id):[],ids=new Set(mine.flatMap(c=>C.studentsIn(state,c.id).map(p=>p.id)));
 const pupils=state.students.filter(p=>!p.archived&&(!year||String(p.year)===year)&&(admin||ids.has(p.id)||state.tutors.some(g=>g.id===p.tutorId&&teacher&&g.teacherId===teacher.id)));
 const pupilIds=new Set(pupils.map(p=>p.id));
 const marks=state.attendance.filter(a=>a.date===t&&pupilIds.has(a.studentId));
 const present=marks.filter(a=>['present','late'].includes(a.mark)).length;
 const groupsToday=(admin?state.classes:mine).filter(c=>!year||String(c.year)===year).flatMap(c=>(c.meetings||[]).filter(m=>m.day===day&&C.meetingInWeek(m,state,t)).map(m=>({c,m}))).sort((a,b)=>a.m.period-b.m.period||a.c.name.localeCompare(b.c.name));
 const upcoming=state.exams.filter(x=>x.date>=t&&(admin||mine.some(c=>c.id===x.classId))).sort((a,b)=>a.date.localeCompare(b.date)).slice(0,3);
 const action=(r,title)=>canRoute(r)?link(r,title):'';
 const notices=state.announcements.filter(n=>!n.classId&&!n.tutorId||admin||mine.some(c=>c.id===n.classId)||state.tutors.some(g=>g.id===n.tutorId&&teacher&&g.teacherId===teacher.id)).slice(-3).reverse();
 const kpi=(label,value,note)=>`<article class="dash-stat"><span>${e(label)}</span><strong>${e(value)}</strong><small>${e(note)}</small></article>`;
 const rows=groupsToday.slice(0,10).map(({c,m})=>{const p=C.PERIODS.find(p=>p.id===m.period);return `<tr><td><strong>${e(p?.start||'')}</strong><small>Lesson ${e(m.period)}</small></td><td><button class="table-link" data-open-class="${e(c.id)}">${e(c.name)}</button><small>${e(c.subject)}</small></td><td>${e(state.rooms.find(r=>r.id===m.roomId)?.name||'Unassigned')}</td><td>${e(state.teachers.find(r=>r.id===c.teacherId)?.name||'Unassigned')}</td><td>${canRoute('attendance')?`<button class="btn soft" data-register="${e(c.id)}" data-register-date="${t}" data-period="${e(m.period)}">Register</button>`:''}</td></tr>`}).join('');
 const points=state.points.filter(p=>pupilIds.has(p.studentId));
 return `<div class="page-head dashboard-title"><div><p>${admin?'SCHOOL OVERVIEW':'MY WORKSPACE'}</p><h1>${admin?'Your school at a glance':'Your teaching day'}</h1><span>${e(state.school.name)} <span aria-hidden="true">·</span> ${e(C.nice(t))} <span class="tag">Week ${C.weekForDate(state,t)}</span></span></div><div class="page-actions">${action('attendance','Take attendance')}${action('manage-timetable','View timetable')}</div></div>${C.schoolClosed(state,t)?`<div class="closure-banner"><b>Registers locked</b><span>${e(C.closureReason(state,t))}</span></div>`:''}
 <div class="dash-three">${card('Quick actions',`<div class="dash-actions">${action('behaviour','Record behaviour or praise')}${action('detentions','Manage detentions')}${action('class-allocation','Move or add students')}${action('oncall','Open On-Call')}</div>`)}${card('Today’s reminders',`<div class="dash-reminder"><span class="dash-round">▤</span><div><strong>${groupsToday.length} scheduled lessons</strong><small>${admin?'In the selected school view':'For your linked teacher account'}</small></div></div>${upcoming.map(x=>`<div class="dash-item"><strong>${e(x.paper)}</strong><small>${e(C.nice(x.date))} · ${e(x.start)}</small></div>`).join('')||empty('No upcoming exams in this view.')}`,action('exams','Exams'))}${card('School notices',notices.map(n=>`<div class="dash-item"><strong>${e(n.title)}</strong><p>${e(n.body)}</p><small>${e(C.nice(n.date))}</small></div>`).join('')||empty('No school notices yet.'),action('tutors','Communities'))}</div>
 <div class="dash-section"><div><h2>${admin?'School snapshot':'My students'}</h2><p>Attendance includes present and late marks in today’s recorded registers.</p></div>${admin?`<label>Year group <select id="dashboardYear"><option value="">All years</option>${[...new Set(state.students.filter(p=>!p.archived).map(p=>p.year))].sort((a,b)=>a-b).map(y=>`<option ${String(y)===year?'selected':''}>${y}</option>`).join('')}</select></label>`:'<span class="tag">Your assigned classes & tutors</span>'}</div>
 <div class="dash-metrics">${kpi('Students',pupils.length,admin?'Current school roll':'In your linked teaching groups')}${kpi('Attendance today',marks.length?Math.round(present/marks.length*100)+'%':'—',marks.length?marks.length+' recorded marks':'No marks recorded')}${kpi('House points',points.filter(p=>p.kind==='reward').reduce((n,p)=>n+Number(p.points||0),0),'All recorded awards in this view')}${kpi('Behaviour points',points.filter(p=>p.kind!=='reward').reduce((n,p)=>n+Number(p.points||0),0),'All recorded points in this view')}</div>
 <div class="dash-bottom">${card(admin?'Today’s teaching':'Your lessons today',rows?`<div class="table-scroll"><table><thead><tr><th>Time</th><th>Class</th><th>Room</th><th>Teacher</th><th>Action</th></tr></thead><tbody>${rows}</tbody></table></div>${groupsToday.length>10?'<p class="dash-empty">Showing the first 10 lessons. Open Week A / B for the complete timetable.</p>':''}`:empty(day>4?'No teaching lessons at the weekend.':!admin&&!teacher?'Your account needs to be linked to a teacher record before your lessons appear.':'No lessons scheduled for this view.'),action('manage-timetable','Full timetable'))}${card('Useful places',`<div class="dash-actions">${action('staffhub','Staff hub & resources')}${action('reports','Reports')}${action('cover','Cover arrangements')}${action('availability','Time out of lessons')}${action('helpdesk','School office helpdesk')}${action('admin','Portal visibility & settings')}</div>`)}</div>`;
}
export function studentShell({data,view,sections,allowed,content,closed}){
 const p=data.student;
 return `<div class="student-redesign"><header class="suite-header"><a class="suite-brand" href="#" data-view="home">${brand}</a><div class="suite-name">${e(data.school.name)}</div><span class="portal-label">Student & family portal</span><button id="portalRefresh">Refresh</button><button id="portalOut">Sign out</button></header><aside class="student-rail"><div class="student-id"><span class="profile-initials">${initials(p.first+' '+p.last)}</span><h2>${e(p.first)} ${e(p.last)}</h2><p>Year ${e(p.year)} · ${e(data.tutors[0]?.name||'')}</p><small>Candidate ${e(p.candidateNumber)}</small>${p.house?`<span class="tag">${e(p.house)} House</span>`:''}</div><nav aria-label="Student portal"><button data-view="home" class="${view==='home'?'active':''}">⌂ <span>My homepage</span></button>${Object.entries(sections).filter(([k])=>allowed(k)).map(([k,t])=>`<button data-view="${k}" class="${view===k?'active':''}"><span>${e(t)}</span><span aria-hidden="true">›</span></button>`).join('')}</nav><p class="rail-help">Need a hand?<br>Speak to your tutor or school office.</p></aside><main id="main" class="student-main">${closed?'<div class="closure-banner">School is closed or closing. Follow your school’s latest instructions.</div>':''}${content}</main><footer class="student-footer">OneEducation · Your school day, connected</footer></div>`;
}
export function studentDashboard({data,allowed,lessons,lesson,detentions}){
 const p=data.student,homework=data.hub.items.filter(i=>i.kind==='homework'),exams=data.exams.filter(x=>x.date>=C.today()).sort((a,b)=>a.date.localeCompare(b.date));
 const go=(v,t)=>`<button class="text-link" data-view="${v}">${e(t)} →</button>`;
 const due=homework.filter(i=>!data.hub.actions.some(a=>a.kind==='submission'&&a.item_id===i.id));
 return `<div class="page-head dashboard-title"><div><p>MY HOMEPAGE</p><h1>Hello, ${e(p.first)}.</h1><span>Ready for your school day? <span class="tag">Week ${C.weekForDate(data,C.today())}</span></span></div><span class="portal-date">${e(C.nice(C.today()))}</span></div>${allowed('exams')&&exams.length?`<div class="student-highlight"><span class="dash-round">▧</span><div><strong>Your next exam · ${e(exams[0].paper)}</strong><small>${e(C.nice(exams[0].date))} · ${e(exams[0].start)}</small></div>${go('exams','Exam timetable')}</div>`:''}${allowed('timetable')?detentions:''}<div class="dash-bottom student-columns"><div class="stack">${allowed('timetable')?card('Your lessons today',lessons.map(lesson).join('')||empty('No lessons scheduled for today.'),go('timetable','Full timetable')):''}${allowed('notices')?card('School notices',data.announcements.slice(-3).reverse().map(n=>`<div class="dash-item"><strong>${e(n.title)}</strong><p>${e(n.body)}</p><small>${e(C.nice(n.date))}</small></div>`).join('')||empty('You’re up to date. No new notices.'),go('notices','View all')):''}</div><div class="stack">${allowed('homework')?card('Homework to do',`<div class="homework-count"><strong>${due.length}</strong><span>awaiting your submission</span></div>${due.slice(0,4).map(i=>`<div class="dash-item"><strong>${e(i.data.title)}</strong><small>${i.data.due?'Due '+e(C.nice(i.data.due)):'No due date set'}</small></div>`).join('')||empty('No homework awaiting submission.')}`,go('homework','Open homework')):''}${card('Make the most of your day',`<div class="dash-actions">${[['classes','Your teaching groups'],['revision','Plan your revision'],['reports','Your reports'],['activities','Clubs & trips'],['evenings','Parents’ evening'],['helpdesk','Ask the school office']].filter(([k])=>allowed(k)).map(([k,t])=>go(k,t)).join('')||empty('Your school will add more sections here.')}</div>`)}</div></div>`;
}


