import * as C from './core.mjs';
import {icon} from './icons.mjs';
const e=(v='')=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const brand='<img class="educate-mark" src="oneeducate-mark.svg" alt="" width="46" height="42"><span class="brand-words"><strong>ONE EDUCATE</strong><small>New Education Through Hope</small></span>';
const roleNames={admin:'Administrator',headteacher:'Headteacher',deputy_head:'Deputy headteacher',assistant_head:'Assistant headteacher',hub:'HUB staff',head_of_year:'Head of Year',deputy_head_of_year:'Deputy Head of Year',office:'School office',timetable_manager:'Timetable manager',teacher:'Teacher',cover_teacher:'Cover teacher',staff:'Staff'};
export const workspaceKind=(role,cap={})=>cap.policies||cap.accounts?'leadership':['hub','head_of_year','deputy_head_of_year'].includes(role)?'pastoral':role==='office'?'office':role==='timetable_manager'?'timetable':['teacher','cover_teacher'].includes(role)?'teacher':'staff';
const initials=n=>e(n.split(/[\s@.]+/).filter(Boolean).slice(0,2).map(s=>s[0]).join('').toUpperCase());
const link=(r,t,cl='')=>`<a class="${cl}" href="#${r}" data-route="${r}"><span>${e(t)}</span>${icon('chevron')}</a>`;
const empty=s=>`<p class="dash-empty">${e(s)}</p>`;
const card=(title,body,action='')=>`<article class="card dash-card"><div class="dash-card-head"><h2>${e(title)}</h2>${action}</div>${body}</article>`;
const groups=[['Students',['students','pupil-records','tutors','class-allocation','manage-pupils','manage-sats']],['Teaching & learning',['classes','manage-classes','manage-timetable','attendance','homework','revision','exams','cover','availability']],['Pastoral & community',['behaviour','detentions','oncall','reports','evenings','activities']],['School & resources',['campus','manage-rooms','manage-staff','manage-houses','school','staffhub','helpdesk']],['Administration',['admin','staff-accounts','manage-policies','funding','lockdown-control']]];
export function staffShell({state,nav,canRoute,route,who,role,demo,dirty,content,capabilities={}}){
 const kind=workspaceKind(demo?'admin':role,demo?{policies:true}:capabilities);
 const homeLabel={leadership:'Overview',teacher:'My day',pastoral:'Support & response',office:'School office',timetable:'Timetable overview',staff:'My workspace'}[kind];
 const favouriteIds={leadership:['home','students','manage-staff','manage-timetable','attendance','oncall','admin'],teacher:['home','classes','attendance','homework','detentions','staffhub'],pastoral:['home','oncall','availability','detentions','students'],office:['home','students','attendance','manage-pupils','helpdesk'],timetable:['home','manage-timetable','manage-classes','manage-rooms','cover'],staff:['home','staffhub','helpdesk','manage-timetable']}[kind];
 const draw=([id,,label])=>`<a href="#${id}" data-route="${id}" ${id===route?'aria-current="page"':''} class="${id===route?'active':''}">${icon(id)}<span>${e(id==='home'?homeLabel:label)}</span></a>`;
 const favourites=favouriteIds.map(id=>nav.find(n=>n[0]===id)).filter(n=>n&&canRoute(n[0]));
 const menu=groups.map(([title,ids])=>{const rows=ids.filter(id=>!favourites.some(n=>n[0]===id)).map(id=>nav.find(n=>n[0]===id)).filter(n=>n&&canRoute(n[0]));return rows.length?`<details class="nav-group" ${rows.some(n=>n[0]===route)?'open':''}><summary>${e(title)}${icon('chevron')}</summary>${rows.map(draw).join('')}</details>`:''}).join('');
 const routeName=nav.find(n=>n[0]===route)?.[2]||homeLabel;
 return `<div class="shell redesign educate"><header class="suite-header"><button class="mobile-menu" id="mobileMenu" aria-label="Toggle navigation" aria-expanded="false">${icon('menu')}</button><a class="suite-brand" href="#home" data-route="home">${brand}</a><label class="global-search">${icon('search')}<input aria-label="Search students and classes" id="globalSearch" placeholder="Search students, classes…" autocomplete="off"><div id="searchResults"></div></label><div class="suite-name">${icon('building')}<span>${e(state.school.name)}</span></div>${canRoute('admin')?link('admin','Administration','header-admin'):''}<div class="suite-user"><span class="user-badge">${initials(who)}</span><span><strong>${e(who)}</strong><small>${e(demo?'Demo administrator':roleNames[role]||'Staff')}</small></span></div><button id="signOut" title="Sign out" aria-label="Sign out">${icon('logout')}</button></header><aside class="rail"><div class="rail-intro"><span>${e(demo?'SAMPLE SCHOOL':roleNames[role]||'STAFF')} WORKSPACE</span></div><nav aria-label="Main navigation"><div class="nav-favourites">${favourites.map(draw).join('')}</div>${menu}</nav><div class="rail-status"><i class="${C.schoolClosed(state)?'closed':''}"></i><div><strong>${C.schoolClosed(state)?'School closed / closing':'School open'}</strong><small>Week ${C.weekForDate(state,C.today())} · ${e(C.nice(C.today()))}</small></div></div></aside><div class="workspace"><div class="workspace-location"><span>${e(state.school.name)}</span>${icon('chevron')}<strong>${e(route==='home'?homeLabel:routeName)}</strong>${demo?'<span class="preview-tag">DEMO · sample data</span>':''}</div><main id="main" tabindex="-1">${content}</main><footer class="savebar"><span id="saveNote">${demo?'Sample workspace · no live changes':'ONE EDUCATE · '+e(state.school.name)}</span><button id="saveState" class="btn primary" ${demo||!dirty?'disabled':''}>${demo?'Demo mode':dirty?'Save changes':'All changes saved'}</button></footer></div></div>`;
}
function dataFor({state,capabilities,demo,email,year='',role}){
 const kind=workspaceKind(role,demo?{policies:true}:capabilities),whole=['leadership','office','timetable','pastoral'].includes(kind),t=C.today();
 const teacher=state.teachers.find(x=>email&&x.email&&x.email.toLowerCase()===email.toLowerCase());
 const mine=teacher?state.classes.filter(c=>c.teacherId===teacher.id):[];
 const ids=new Set(mine.flatMap(c=>C.studentsIn(state,c.id).map(p=>p.id)));
 const pupils=state.students.filter(p=>!p.archived&&(!year||String(p.year)===year)&&(whole||ids.has(p.id)||teacher&&state.tutors.some(g=>g.id===p.tutorId&&g.teacherId===teacher.id)));
 const pupilIds=new Set(pupils.map(p=>p.id)),marks=state.attendance.filter(a=>a.date===t&&pupilIds.has(a.studentId));
 const lessons=(whole?state.classes:mine).filter(c=>!year||String(c.year)===year).flatMap(c=>(c.meetings||[]).filter(m=>m.day===C.weekday(t)&&C.meetingInWeek(m,state,t)).map(m=>({c,m,p:C.PERIODS.find(p=>p.id===m.period)}))).sort((a,b)=>a.m.period-b.m.period||a.c.name.localeCompare(b.c.name));
 const notices=state.announcements.filter(n=>!n.classId&&!n.tutorId||whole||mine.some(c=>c.id===n.classId)||teacher&&state.tutors.some(g=>g.id===n.tutorId&&g.teacherId===teacher.id)).slice(-3).reverse();
 return {kind,whole,t,teacher,pupils,pupilIds,marks,lessons,notices};
}
const metric=(label,value,note,type,accent='')=>`<article class="dash-stat ${accent}"><span class="stat-symbol">${icon(type)}</span><div><span>${e(label)}</span><strong>${e(value)}</strong><small>${e(note)}</small></div></article>`;
const attendance=marks=>marks.length?Math.round(marks.filter(a=>['present','late'].includes(a.mark)).length/marks.length*1000)/10+'%':'—';
function noticesCard(notices){return card('School notices',notices.map(n=>`<div class="notice-row">${icon('bell')}<div><strong>${e(n.title)}</strong><p>${e(n.body)}</p><small>${e(C.nice(n.date))}</small></div></div>`).join('')||empty('No notices have been published yet.'))}
function timetableCard(d,state,action,canRoute){
 const rows=d.lessons.slice(0,8).map(({c,m,p})=>`<tr><td><strong>${e(p?.start||'')}</strong><small>P${e(m.period)}</small></td><td><button class="table-link" data-open-class="${e(c.id)}">${e(c.name)}</button><small>${e(c.subject)}</small></td><td>${e(state.rooms.find(r=>r.id===m.roomId)?.name||'Unassigned')}</td><td>${e(state.teachers.find(r=>r.id===c.teacherId)?.name||'Unassigned')}</td><td>${canRoute('attendance')?`<button class="btn soft" data-register="${e(c.id)}" data-register-date="${d.t}" data-period="${e(m.period)}">Open register</button>`:''}</td></tr>`).join('');
 return card(d.whole?'Today at school':'Today’s lessons',rows?`<div class="table-scroll"><table><thead><tr><th>Time</th><th>Class</th><th>Room</th><th>Staff</th><th></th></tr></thead><tbody>${rows}</tbody></table></div>${d.lessons.length>8?'<p class="dash-empty">First 8 lessons shown. Open the full timetable to see all lessons.</p>':''}`:empty(C.weekday(d.t)>4?'No teaching lessons at the weekend.':!d.whole&&!d.teacher?'Your school needs to link your email to a teacher record before your lessons appear.':'No lessons scheduled today.'),action('manage-timetable','Full timetable'));
}
function yearChart(d,state){const years=[...new Set(d.pupils.map(p=>p.year))].sort((a,b)=>a-b);return card('Attendance by year group',`<div class="year-bars">${years.map(y=>{const ids=new Set(d.pupils.filter(p=>p.year===y).map(p=>p.id)),marks=d.marks.filter(a=>ids.has(a.studentId)),value=attendance(marks);return `<div><span>Year ${e(y)}</span><strong>${value}</strong><span class="bar-track" aria-hidden="true"><i style="width:${value==='—'?0:parseFloat(value)}%"></i></span></div>`}).join('')||empty('Add students to see year groups here.')}</div><p class="chart-note">Today’s recorded marks · present and late included. No marks are shown as —.</p>`)}
export function staffDashboard(args){
 const {state,canRoute,capabilities,demo,year='',role='teacher'}=args,d=dataFor({...args,role}),action=(r,title)=>canRoute(r)?link(r,title):'';
 const heading={leadership:'School overview',teacher:'Your teaching day',pastoral:'Support & response',office:'School office',timetable:'Timetable overview',staff:'Your workspace'}[d.kind];
 const copy={leadership:'Key information and activity across your school.',teacher:'Your lessons, students and key tasks for today.',pastoral:'Relevant alerts, lesson removals and planned support.',office:'Student records, daily attendance and school enquiries.',timetable:'Teaching groups, rooms and the week ahead.',staff:'Your school tools and the latest updates.'}[d.kind];
 const quick=[['attendance','Open registers'],['behaviour','Record points'],['detentions','Detention board'],['oncall','Request support'],['class-allocation','Move students'],['admin','Administration']].filter(([r])=>canRoute(r));
 const head=`<div class="page-head dashboard-title"><div><p>ONE EDUCATE <span class="tag">Week ${C.weekForDate(state,d.t)}</span></p><h1>${heading}</h1><span>${copy}</span></div><div class="page-actions"><span class="date-chip">${icon('calendar')}${e(C.nice(d.t))}</span>${quick.length?`<details class="quick-menu"><summary>${icon('plus')}Quick actions</summary><div>${quick.map(([r,t])=>action(r,t)).join('')}</div></details>`:''}</div></div>${C.schoolClosed(state,d.t)?`<div class="closure-banner"><b>Registers locked</b><span>${e(C.closureReason(state,d.t))}</span></div>`:''}`;
 if(d.kind==='pastoral')return head+`<div id="pastoral-live" aria-live="polite">${card('Relevant alerts',empty('Loading your permitted support information…'))}</div><div class="dash-bottom">${card('Scheduled out of lesson',supportRows(state),action('availability','Manage arrangements'))}${card('Pastoral tools',`<div class="dash-actions">${action('oncall','On-Call & lesson removals')}${action('detentions','Detention board & downloads')}${action('class-allocation','Class allocation')}${action('students','Student search')}${action('behaviour','Record behaviour or praise')}</div>`)}</div>`;
 if(d.kind==='teacher'||d.kind==='staff'){
  const clock=new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/London',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date());
  const next=d.lessons.find(l=>l.p&&C.mins(l.p.end)>C.mins(clock));
  const nextPanel=next?`<article class="next-lesson"><div class="next-top"><span>${icon('calendar')}UP NEXT</span><span class="tag">P${next.m.period}</span></div><h2>${e(next.p.start)} · ${e(next.c.name)}</h2><p>${icon('building')}${e(state.rooms.find(r=>r.id===next.m.roomId)?.name||'Room unassigned')} <span>· ${C.studentsIn(state,next.c.id).length} students</span></p>${canRoute('attendance')?`<button class="btn primary" data-register="${e(next.c.id)}" data-register-date="${d.t}" data-period="${next.m.period}">Open register ${icon('arrow')}</button>`:action('manage-timetable','View timetable')}</article>`:card('Your next lesson',empty(d.lessons.length?'Your scheduled lessons have finished for today.':d.teacher?'No lessons scheduled today.':'Ask your school to link your email to your teacher profile.'),action('manage-timetable','View timetable'));
  return head+`<div class="dash-bottom teacher-top">${nextPanel}${card('Quick actions',`<div class="dash-actions">${action('behaviour','Award points / record behaviour')}${action('oncall','Request support')}${action('detentions','Add a detention')}${action('homework','Set and review homework')}</div>`)}</div><div class="dash-bottom">${timetableCard(d,state,action,canRoute)}${noticesCard(d.notices)}</div><div class="dash-metrics secondary-metrics">${metric('My students',d.pupils.length,'Your classes and tutor groups','people')}${metric('Attendance today',attendance(d.marks),d.marks.length+' recorded marks','register')}${metric('House points',state.points.filter(p=>d.pupilIds.has(p.studentId)&&p.kind==='reward').reduce((n,p)=>n+Number(p.points||0),0),'Recorded awards for your students','trophy')}</div>`;
 }
 const expected=d.lessons.reduce((n,{c,m})=>n+C.studentsIn(state,c.id).filter(p=>d.pupilIds.has(p.id)&&!state.attendance.some(a=>a.studentId===p.id&&a.date===d.t&&Number(a.period)===m.period)).length,0);
 const pending=d.lessons.filter(({c,m})=>C.studentsIn(state,c.id).some(p=>d.pupilIds.has(p.id)&&!state.attendance.some(a=>a.studentId===p.id&&a.date===d.t&&Number(a.period)===m.period))).length;
 const covers=state.covers.filter(c=>c.date===d.t).length;
 const filters=`<div class="dashboard-filter"><span>Today’s school snapshot</span><label>Year group <select id="dashboardYear"><option value="">All years</option>${[...new Set(state.students.filter(p=>!p.archived).map(p=>p.year))].sort((a,b)=>a-b).map(y=>`<option ${String(y)===year?'selected':''}>${y}</option>`).join('')}</select></label></div>`;
 return head+filters+`<div class="dash-metrics">${metric('Students',d.pupils.length,'Current roll in this view','people')}${metric('Attendance',attendance(d.marks),d.marks.length+' recorded marks today','chart')}${metric('Cover today',covers,'Saved school-wide arrangements','cover','amber')}${metric('Registers pending',pending,expected+' lesson marks still to record','register',pending?'amber':'')}</div><div class="dash-bottom overview-top">${yearChart(d,state)}${card('Needs your attention',`<div class="attention-list">${canRoute('attendance')?`<a href="#attendance" data-route="attendance">${icon('register')}<span><strong>Unmarked registers</strong><small>Includes lessons later today</small></span><b>${pending}</b>${icon('chevron')}</a>`:''}${canRoute('cover')?`<a href="#cover" data-route="cover">${icon('cover')}<span><strong>Cover arrangements</strong><small>Check staff availability</small></span><b>${covers}</b>${icon('chevron')}</a>`:''}${canRoute('oncall')?`<a href="#oncall" data-route="oncall">${icon('bell')}<span><strong>On-Call & support</strong><small>View alerts relevant to your role</small></span>${icon('chevron')}</a>`:''}${canRoute('admin')?`<a href="#admin" data-route="admin">${icon('shield')}<span><strong>Administration</strong><small>School settings and portal controls</small></span>${icon('chevron')}</a>`:''}${d.kind==='timetable'?action('manage-rooms','Buildings & rooms')+action('manage-classes','Classes & tutors'):''}${d.kind==='office'?action('manage-pupils','Student imports')+action('helpdesk','Office enquiries'):''}</div>`)}</div><div class="dash-bottom">${timetableCard(d,state,action,canRoute)}${noticesCard(d.notices)}</div>`;
}
const activeSupport=a=>!a.cancelled&&(a.recurring?(!a.end||a.end>=C.today()):a.start>=C.today());
function supportRows(state){const rows=(state.availability||[]).filter(a=>activeSupport(a)&&a.personType==='student').slice(0,6);return rows.length?`<div class="table-scroll"><table class="support-table"><thead><tr><th>Student</th><th>When</th><th>Lessons</th><th>Week</th></tr></thead><tbody>${rows.map(a=>{const p=state.students.find(p=>p.id===a.personId);return `<tr><td>${e(p?p.first+' '+p.last:'Former student')}</td><td>${e(a.recurring?C.DAYS[a.day]:C.nice(a.start))}<small>${a.recurring?'Weekly arrangement':'One date'}</small></td><td>${e((a.periods||[]).map(p=>'P'+p).join(', '))}</td><td>${e(a.week)}</td></tr>`}).join('')}</tbody></table></div>`:empty('No current student support arrangements.');}
export function pastoralOverview(store,state){
 const alerts=(store.items||[]).filter(x=>x.kind==='alert'&&!x.data.cancelled),removals=(state.removals||[]).filter(x=>x.date===C.today());
 return `<div class="dash-metrics pastoral-metrics">${metric('Open alerts',alerts.length,'Visible to your account','bell',alerts.length?'amber':'')}${metric('Lesson removals',removals.length,'Recorded today','clock')}${metric('Support arrangements',(store.items||[]).filter(x=>x.kind==='availability'&&activeSupport(x.data)).length,'Active or upcoming','calendar')}</div>${card('On-Call / support queue',alerts.length?`<div class="table-scroll"><table class="support-table"><thead><tr><th>Request</th><th>Priority</th><th>Audience</th><th>Created</th><th></th></tr></thead><tbody>${alerts.slice(0,8).map(x=>`<tr><td><strong>${e(x.data.type)}</strong><small>${x.data.type==='Safeguarding'?'Restricted request · open securely':e((x.data.body||'').slice(0,100))}</small></td><td><span class="tag ${['Urgent','Emergency'].includes(x.data.priority)?'urgent':''}">${e(x.data.priority)}</span></td><td>${e(x.data.target==='everyone'?'All staff':x.data.target)}<small>${e(x.data.targetId||'')}</small></td><td>${e((x.created_at||'').slice(0,10))}</td><td><a class="btn soft" href="#oncall">View</a></td></tr>`).join('')}</tbody></table></div>`:empty('No open alerts for your account.'),'<a class="text-link" href="#oncall">Open On-Call →</a>')}`;
}


export function studentShell({data,view,sections,allowed,content,closed}){
 const p=data.student;
 return `<div class="student-redesign"><header class="suite-header"><a class="suite-brand" href="#" data-view="home">${brand}</a><div class="suite-name">${e(data.school.name)}</div><span class="portal-label">Student & family portal</span><button id="portalRefresh">Refresh</button><button id="portalOut">Sign out</button></header><aside class="student-rail"><div class="student-id"><span class="profile-initials">${initials(p.first+' '+p.last)}</span><h2>${e(p.first)} ${e(p.last)}</h2><p>Year ${e(p.year)} · ${e(data.tutors[0]?.name||'')}</p><small>Candidate ${e(p.candidateNumber)}</small>${p.house?`<span class="tag">${e(p.house)} House</span>`:''}</div><nav aria-label="Student portal"><button data-view="home" class="${view==='home'?'active':''}">${icon('home')} <span>My homepage</span></button>${Object.entries(sections).filter(([k])=>allowed(k)).map(([k,t])=>`<button data-view="${k}" class="${view===k?'active':''}">${icon(k)}<span>${e(t)}</span></button>`).join('')}</nav><p class="rail-help">Need a hand?<br>Speak to your tutor or school office.</p></aside><main id="main" class="student-main">${closed?'<div class="closure-banner">School is closed or closing. Follow your school’s latest instructions.</div>':''}${content}</main><footer class="student-footer">ONE EDUCATE · Your school day, connected</footer></div>`;
}
export function studentDashboard({data,allowed,lessons,lesson,detentions}){
 const p=data.student,homework=data.hub.items.filter(i=>i.kind==='homework'),exams=data.exams.filter(x=>x.date>=C.today()).sort((a,b)=>a.date.localeCompare(b.date));
 const go=(v,t)=>`<button class="text-link" data-view="${v}">${e(t)} →</button>`;
 const due=homework.filter(i=>!data.hub.actions.some(a=>a.kind==='submission'&&a.item_id===i.id));
 return `<div class="page-head dashboard-title"><div><p>MY HOMEPAGE</p><h1>Hello, ${e(p.first)}.</h1><span>Ready for your school day? <span class="tag">Week ${C.weekForDate(data,C.today())}</span></span></div><span class="portal-date">${e(C.nice(C.today()))}</span></div>${allowed('exams')&&exams.length?`<div class="student-highlight"><span class="dash-round">${icon('file')}</span><div><strong>Your next exam · ${e(exams[0].paper)}</strong><small>${e(C.nice(exams[0].date))} · ${e(exams[0].start)}</small></div>${go('exams','Exam timetable')}</div>`:''}${allowed('timetable')?detentions:''}<div class="dash-bottom student-columns"><div class="stack">${allowed('timetable')?card('Your lessons today',lessons.map(lesson).join('')||empty('No lessons scheduled for today.'),go('timetable','Full timetable')):''}${allowed('notices')?card('School notices',data.announcements.slice(-3).reverse().map(n=>`<div class="dash-item"><strong>${e(n.title)}</strong><p>${e(n.body)}</p><small>${e(C.nice(n.date))}</small></div>`).join('')||empty('You’re up to date. No new notices.'),go('notices','View all')):''}</div><div class="stack">${allowed('homework')?card('Homework to do',`<div class="homework-count"><strong>${due.length}</strong><span>awaiting your submission</span></div>${due.slice(0,4).map(i=>`<div class="dash-item"><strong>${e(i.data.title)}</strong><small>${i.data.due?'Due '+e(C.nice(i.data.due)):'No due date set'}</small></div>`).join('')||empty('No homework awaiting submission.')}`,go('homework','Open homework')):''}${card('Make the most of your day',`<div class="dash-actions">${[['classes','Your teaching groups'],['revision','Plan your revision'],['reports','Your reports'],['activities','Clubs & trips'],['evenings','Parents’ evening'],['helpdesk','Ask the school office']].filter(([k])=>allowed(k)).map(([k,t])=>go(k,t)).join('')||empty('Your school will add more sections here.')}</div>`)}</div></div>`;
}




